
---

- hosts: localhost
  gather_facts: false
  
  vars_files:
    - "{{ lookup('env','CONFDIR') }}/variables/account.yml"
    - "{{ lookup('env','BASEDIR') }}/includes/dockerapps/templates/generique/generique.yml"

  tasks:

    - name: Checking for existing app data
      stat:
        path: "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/authelia/configuration.yml"
      register: check

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'gui'

    - name: "Set DNS Record on CloudFlare"
      include_tasks: "{{ lookup('env','BASEDIR') }}/includes/config/roles/cloudflare/tasks/main.yml"
      vars:
        subdomain: "{{sub[pgrole][pgrole] if sub_enabled else pgrole}}"
      when: cloudflare_enabled



    - name: Install nginx
      become: yes
      apt:
        state: present
        name:
          - "nginx"
      ignore_errors: true

    - name: Install common packages
      become: yes
      apt:
        state: present
        name:
          - "php-fpm"
          - "php-curl"
          - "php-dom"
          - "php-gd"
          - "composer"
      ignore_errors: true

    - name: Import nginx default
      become: yes
      template:
        src: "{{ lookup('env','BASEDIR') }}/includes/config/roles/nginx/templates/default.j2"
        dest: /etc/nginx/sites-available/default
        force: yes


    - name: Change log file owner
      become: yes
      file:
        path: /var/log/nginx
        state: directory
        owner: "{{ lookup('env','USER') }}"

    - name: stopped Systemd nginx
      become: yes
      systemd:
        name: 'nginx.service'
        state: stopped

    - name: Change user
      become: yes
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^user '
        line: "user {{ lookup('env','USER') }};"

    - name: Version php-fpm
      become: yes
      shell: ls /etc/php
      register: fpm
      
    - name: Chown php-fpm
      become: yes
      shell: chown "{{ lookup('env','USER') }}"  /var/run/php/php*sock
      
    - name: change user in php
      become: yes
      lineinfile:
        path: "/etc/php/{{ fpm.stdout }}/fpm/pool.d/www.conf"
        line: "{{ item }} = {{ lookup('env','USER') }}"
        regexp: "^{{ item }} ="
      with_items:
        - user
        - group
        - listen.owner
        - listen.group
        
    - name: restart php-fpm service
      become: yes
      service:
        name: "php{{ fpm.stdout }}-fpm"
        state: restarted



    - name: Import middlewares-chains.toml
      become: yes
      template:
        src: "{{ lookup('env','BASEDIR') }}/includes/dockerapps/templates/traefik/nginx.toml.j2"
        dest: "{{ lookup('env','CONFDIR') }}/docker/traefik/rules/nginx.toml"
        force: yes
        owner: "{{ lookup('env','USER') }}"
        


    - name: started Systemd nginx
      become: yes
      systemd:
        name: 'nginx.service'
        state: started

    - name: Create www directories
      become: yes
      file: "path={{ item }} state=directory mode=0775 owner={{ lookup('env','USER') }} group={{ lookup('env','USER') }} recurse=yes"
      with_items:
        - /var/www/{{user.domain}}

    - name: Clone SSD
      git:
        repo: https://github.com/projetssd/ssdsite.git/
        dest: /var/www/{{user.domain}}
        version: HEAD
        force: yes

    - name: Composer install
      shell: composer install
      args:
        chdir: /var/www/{{user.domain}}


