#!/bin/bash
---

- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    - name: 'Import backup config'
      become: yes
      template:
        src: /opt/seedbox-compose/includes/config/roles/backup/templates/backup.j2
        dest: /usr/local/bin/backup
        owner: "root"
        group: "root"
        mode: 0755
        force: yes

    - name: 'Import restore config'
      become: yes
      template:
        src: /opt/seedbox-compose/includes/config/roles/backup/templates/restore.j2
        dest: /usr/local/bin/restore
        owner: "root"
        group: "root"
        mode: 0755
        force: yes
    
    - name: Set cron
      become: yes
      cron: 
        name: "backup"
        minute: "0"
        hour: "3"
        weekday: "6"
        job: "/usr/local/bin/backup"




